import type { Metadata } from "next";
import { auth } from "@/auth";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import ReduxProvider from "@/redux/ReduxProvider";
import ToasterProvider from "@/providers/ToasterProvider";
import { StopwatchProvider } from "@/providers/StopWatchProvider";
import { Sarabun } from "next/font/google";
import { SpeedInsights } from "@vercel/speed-insights/next";
import TanstackProvider from "@/providers/TanstackProvider";

const sarabun = Sarabun({
  subsets: ["thai", "latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "ExamOnline",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="th">
      <body className={sarabun.className}>
        <TanstackProvider>
          <ReduxProvider>
            <SessionProvider session={session}>
              <StopwatchProvider>
                {children}
                <SpeedInsights />
              </StopwatchProvider>
              <ToasterProvider />
            </SessionProvider>
          </ReduxProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}
