import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "./[...nextauth]/authOptions";
import NextAuthProvider from "@/providers/NextAuthProvider";
import ReduxProvider from "@/redux/ReduxProvider";
import dynamic from "next/dynamic";
import ToasterProvider from "@/providers/ToasterProvider"
import { StopwatchProvider } from "@/providers/StopWatchProvider";
import { Sarabun } from "next/font/google";



const sarabun = Sarabun({
  subsets: ["thai", "latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "ExamSphere",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  

  return (
    <html lang="th">
      <body className={sarabun.className}>
        <ReduxProvider>
          <NextAuthProvider session={session}>
              <StopwatchProvider>
                {children}
              </StopwatchProvider>
              <ToasterProvider />
          </NextAuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
